<?php

namespace Tests\Feature\Muwakha;

use App\Models\Account;
use App\Models\AccountType;
use App\Models\BankType;
use App\Models\Currency;
use App\Models\MuwakhaFamily;
use App\Models\Project;
use App\Models\ProjectStatus;
use App\Models\ProjectSuper;
use App\Support\Muwakha\MuwakhaReference;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\URL;
use Tests\TestCase;

/**
 * Shared setup for the Muwakha Families suite: schema-only SQLite :memory:,
 * every real migration except the two pre-existing MySQL-only ones — the same
 * established approach as Tests\Feature\Audit\AuditTestCase.
 *
 * The Muwakha reference data (the `أفراد` account type, the currencies and the
 * `مشروع المؤاخاة` root ProjectSuper) is created by the real migrations,
 * EXCEPT `أفراد` and the currencies, which are live UI-entered data on the
 * real database and have no migration. Those are created here per test, which
 * is also what proves the resolvers look them up by name rather than by a
 * hard-coded id.
 *
 * Three currencies are available so the currency-selection paths can be
 * exercised for real; `familyData()` defaults to the shekel, and any test may
 * override `currency_id` with the dollar or the euro.
 */
abstract class MuwakhaTestCase extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        $mysqlOnly = [
            '2026_06_24_000005_backfill_denormalized_currency_and_amounts',
            '2026_06_24_000009_add_supporting_indexes_for_financial_report',
        ];

        $paths = collect(glob(base_path('database/migrations/*.php')))
            ->reject(fn (string $path) => str_contains($path, $mysqlOnly[0]) || str_contains($path, $mysqlOnly[1]))
            ->map(fn (string $path) => 'database/migrations/'.basename($path))
            ->values()
            ->all();

        Artisan::call('migrate', [
            '--path' => $paths,
            '--realpath' => false,
            '--force' => true,
        ]);

        // Required by every Filament HTTP/Livewire suite in this repository
        // (see CrudRedirectStandardTest): without it the resource URLs
        // generated by getUrl() do not match the registered panel routes and
        // every page request 404s.
        URL::forceRootUrl('http://localhost');
    }

    /**
     * The `أفراد` account type — live UI-entered reference data on the real
     * database, so it has no migration and must be created per test.
     */
    protected function seedIndividualsAccountType(): AccountType
    {
        return AccountType::create(['name' => MuwakhaReference::ACCOUNT_TYPE_NAME]);
    }

    /**
     * The three live OMS currencies — likewise UI-entered reference data. The
     * `name` is the display label the whole feature uses (account-name suffix,
     * table column, view page, both exports), so these are the values the
     * assertions read.
     */
    protected function seedShekelCurrency(): Currency
    {
        return $this->seedCurrency('شيكل', 'ILS', '₪');
    }

    protected function seedDollarCurrency(): Currency
    {
        return $this->seedCurrency('دولار', 'USD', '$', isBase: true);
    }

    protected function seedEuroCurrency(): Currency
    {
        return $this->seedCurrency('يورو', 'EUR', '€');
    }

    /**
     * firstOrCreate keyed on the UNIQUE `code`, so the helpers are safe to call
     * repeatedly within one test (familyData() resolves the default currency on
     * every call).
     */
    protected function seedCurrency(string $name, string $code, string $symbol, bool $isBase = false): Currency
    {
        return Currency::firstOrCreate(
            ['code' => $code],
            ['name' => $name, 'symbol' => $symbol, 'is_base' => $isBase],
        );
    }

    protected function seedBankType(string $name = 'بنك فلسطين'): BankType
    {
        return BankType::firstOrCreate(['name' => $name]);
    }

    /**
     * The full reference set every family create/update path needs.
     *
     * @return array{account_type: AccountType, currency: Currency, bank_type: BankType}
     */
    protected function seedMuwakhaReference(): array
    {
        return [
            'account_type' => $this->seedIndividualsAccountType(),
            'currency' => $this->seedShekelCurrency(),
            'bank_type' => $this->seedBankType(),
        ];
    }

    /**
     * The `مشروع المؤاخاة` root ProjectSuper, created by the real reference
     * data migration.
     */
    protected function muwakhaRoot(): ProjectSuper
    {
        return ProjectSuper::where('name', MuwakhaReference::PROJECT_SUPER_NAME)->firstOrFail();
    }

    protected function projectStatus(): ProjectStatus
    {
        return ProjectStatus::firstOrCreate(['name' => 'غير مكتمل'], ['color' => '#ff0000']);
    }

    /**
     * A real Muwakha project — an ordinary Project whose project_super_id
     * points at the `مشروع المؤاخاة` root.
     */
    protected function makeMuwakhaProject(string $name = 'مؤاخاة كاف 2026'): Project
    {
        return Project::create([
            'name' => $name,
            'project_super_id' => $this->muwakhaRoot()->id,
            'project_status_id' => $this->projectStatus()->id,
        ]);
    }

    /**
     * A project under a DIFFERENT root — the forged-request negative case.
     */
    protected function makeUnrelatedProject(string $name = 'مشروع الطعام 2026'): Project
    {
        $otherSuper = ProjectSuper::create(['name' => 'الطعام', 'code_prefix' => 'FOOD']);

        return Project::create([
            'name' => $name,
            'project_super_id' => $otherSuper->id,
            'project_status_id' => $this->projectStatus()->id,
        ]);
    }

    /**
     * Valid family form data. Override any key per test.
     *
     * @param  array<string, mixed>  $overrides
     * @return array<string, mixed>
     */
    protected function familyData(array $overrides = []): array
    {
        return array_merge([
            'martyr_name' => 'أحمد محمد',
            'martyr_national_id' => '0412345678',
            'martyr_date_of_birth' => '1990-01-01',
            'martyrdom_date' => '2024-05-10',
            'children_count' => 3,
            'guardian_name' => 'فاطمة أحمد',
            'guardian_national_id' => '0498765432',
            'guardian_date_of_birth' => '1992-03-04',
            'guardian_phone' => '0599123456',
            'account_holder_name' => 'فاطمة أحمد محمد',
            'account_code' => '123456',
            'bank_type_id' => $this->seedBankType()->id,
            'currency_id' => $this->seedShekelCurrency()->id,
            'iban' => null,
            'notes' => null,
        ], $overrides);
    }

    protected function accountOf(MuwakhaFamily $family): Account
    {
        return Account::withTrashed()->findOrFail($family->account_id);
    }
}
